name: build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
        
      - name: checkout
        uses: actions/checkout@v2
      
      - name: build and test
        run: go test -timeout=60s ./...
        
      - name: build image bot
        run: docker build --build-arg SKIP_TEST=true .
        
      - name: build image srv
        run: docker build -f Server.Dockerfile --build-arg SKIP_TEST=true .
