name: publish

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
        
      - name: checkout
        uses: actions/checkout@v2
      
      - name: build and test
        run: go test -mod=vendor -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...
        env:
          GO111MODULE: on
      
      - name: install golangci-lint and goveralls
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.23.6
          GO111MODULE=off go get -u -v github.com/mattn/goveralls
      
      - name: run linters
        run: $GITHUB_WORKSPACE/golangci-lint run

      - name: submit coverage
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

  cd:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      
      - name: build image bot
        run: docker build -t bot --build-arg SKIP_TEST=true .
        
      - name: build image srv
        run: docker build -f Server.Dockerfile -t server_bot --build-arg SKIP_TEST=true .
      
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Tag
        run: |
          docker tag bot ${{ secrets.DOCKER_USER }}/vkdigest_bot:master
          docker tag server_bot ${{ secrets.DOCKER_USER }}/vkdigest_bot_server:master
          
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/vkdigest_bot:master
          docker push ${{ secrets.DOCKER_USER }}/vkdigest_bot_server:master
